### ISSUE TITLE
Extract k values

### ISSUE THREAD

**Issue by bowenjfung** [drbenvincent/delay-discounting-analysis#1]
Hi there,

Great toolbox!

Is it possible to extract the estimated discount rate at a participant level?

**Comment by drbenvincent** [comment]
Thanks, hope it's useful.

The first thing I've done is to clarify in `SCRIPT.m` where the univariate summary information is. If you create a model called `hModel` as in the demo provided, then summary information at the group and participant level is stored in a structure `hModel.analyses.univariate` So you can for example get participant level estimates of the slope of the discount rate into a nice table with a command like:

```
participant_level_m = array2table([hModel.analyses.univariate.m.mode' hModel.analyses.univariate.m.CI95'],...
'VariableNames',{'posteriorMode' 'CI5' 'CI95'})
```

resulting in something like this...
![screen shot 2015-11-10 at 16 39 06](https://cloud.githubusercontent.com/assets/6765047/11068528/a189827e-87c9-11e5-9d03-ed67143a7ded.png)

I'm not sure if this is exactly what you are after? I will soon add a function to automatically generate these tables and export them to a text file.

There is another way to interpret your question however. At the moment we make estimates on `m` and `c` which gives you the magnitude effect slope. If you want to simplify this to get a distribution of discount rates `k` then I will be writing a function to let you do this soon as well.

**Comment by drbenvincent** [comment]
Following up on the last point. If you want k values then you can now do this. I have added a method to the model class which allows to you calculate group and participant level estimates of discount rate, log(k) for a specified reward magnitude.

Have added some example code into the demo `SCRIPT.m` which calculates and plots this.

So code like the following will now do this for you

```
plotFlag=true;
hModel.conditionalDiscountRates(100, plotFlag);
```

and you get a nice Matlab table of discount rates
![screen shot 2015-11-10 at 16 36 13](https://cloud.githubusercontent.com/assets/6765047/11068435/2d2e1a70-87c9-11e5-9f0a-09a0d69d0047.png)
And plots of the full posterior (predictive) distributions for group and participant
![screen shot 2015-11-10 at 16 36 46](https://cloud.githubusercontent.com/assets/6765047/11068448/4356a722-87c9-11e5-9007-56fa7157d04f.png)

I think that answers your question? And let me know if I can add anything more.

**Comment by bowenjfung** [comment]
Hi Benjamin,

This is exactly what I was after (and more)!

Thanks very much.
