### ISSUE TITLE
problem getting demo to run

### ISSUE THREAD

**Issue by benepp** [drbenvincent/delay-discounting-analysis#117]
Sorry to bother you with this. I would like to use the demo but I can't get the MCMC sampling to run. I am sure this is a trivial issue and has to do with the fact that a path is not set properly. But I don't get were the path is set. Any help is appreciated.
Below please find the error message.

Error using matjags (line 288)
Error from dos environment: Dokumente: Undefined variable.
Welcome to JAGS 4.2.0 on Wed Sep 21 15:24:00 2016
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Failed to open file
/Users/bene/Documents/benmob/delay-discounting-analysis/~/Documents/benmob/delay-discounting-analysis/ddToolbox/models/hierarchicalME.txt

Error in MatjagsWrapper/invokeSampler (line 57)
            [samples, stats] = matjags(...
Error in MatjagsWrapper/conductInference (line 44)
            mcmc = obj.invokeSampler();
Error in Model/conductInference (line 67)
            obj.mcmc = obj.sampler.conductInference( obj , obj.data );
Error in SCRIPT (line 67)
hModel.conductInference()

Thanks!
ben

**Comment by drbenvincent** [comment]
Hi Ben. I really appreciate bug reports and feedback! I'll get on this in the next day or so (I have to balance it with my teaching). In the mean time, it looks like there is a problem with the path as you say `/Users/bene/Documents/benmob/delay-discounting-analysis/~/Documents/benmob/delay-discounting-analysis/ddToolbox/models/hierarchicalME.txt`

I'll look into this to solve the underlying problem, but in the mean time, if you are providing paths as in the demo code, you could experiment with providing absolute paths (i.e. not using `~`).

Can you let me know the full code you are using to help me track it down? I'll try to do a fix as soon as I can.

(PS the in-development code for the next release should hopefully be more robust against things like this).

**Comment by benepp** [comment]
Thanks!! It runs when setting the absolute paths, I tried that before, but probably not for all of them. Note, that I had to remove the following line: %toolboxPath = setToolboxPath(toolboxPath); at line 18 to make it run. It now crashes when trying to export the parameter estimates (see below). I am not yet sure what the problem is but it probably has to do with the output format of the model.
best ben

Error using array2table (line 62)
The RowNames property must contain one name for each row in the table.
Error in mcmcContainer/exportParameterEstimates (line 63)
            paramEstimateTable = array2table(paramEstimates,...
Error in Model/exportParameterEstimates (line 91)
            paramEstimateTable = obj.mcmc.exportParameterEstimates(...
Error in SCRIPT (line 70)
hModel.exportParameterEstimates();

**Comment by drbenvincent** [comment]
Just so you know, I'm about to release a new version of the code which will have quite a few bug fixes and a few changes to the way the code is called. I'm aiming to release this over the weekend or Monday. It's quite likely that the bug will disappear with this new code. If you didn't want to wait, you could switch to the dev branch (to get the latest code) and see if it fixes the problem. If not, then I'm happy to Skype to get to the bottom of it (same username as I have on here). But by Sunday/Monday the new version will be released with some more documentation on the wiki (and fewer bugs!).

**Comment by drbenvincent** [comment]
I've just released [version 1.4](https://github.com/drbenvincent/delay-discounting-analysis/releases). It might be worth doing a fresh install and consulting the updated [install instructions](https://github.com/drbenvincent/delay-discounting-analysis/wiki/1.-Getting-Started). Note that the demo file is changed quite a bit.

Please let me know if it works or not, and what version of Matlab you are running.

Fingers crossed

**Comment by benepp** [comment]
Hi,

Just to let you know: It works well for the magnitude models but crashes for discount rate models. not sure what the issue is...

best ben

Error using myExport
'/Users/bene/Documents/benmob/delay-discounting-analysis/dlstudy_s1/output/my_analysis' is not a recognized parameter. For
a list of valid name-value pair arguments, see the documentation for myExport.

Error in myExport (line 11)
p.parse(savePath, saveName, varargin{:});

Error in plotLOGKclusters (line 49)
    myExport('summary_plot',...

Error in Model/plot (line 197)
            obj.plotFuncs.clusterPlotFunc(...

Error in Model/conductInference (line 106)
                obj.plot( 'shouldExportPlots', obj.shouldExportPlots )

Error in ModelHierarchicalLogK (line 29)
            obj = obj.conductInference();

Error in young_s1 (line 98)
model = ModelHierarchicalLogK(...

**Comment by drbenvincent** [comment]
This is now fixed in the latest commit - you should be able to run if you can update to the latest commit. More fixes soon also.
