### ISSUE TITLE
Some error in adding toolbox subpaths

### ISSUE THREAD

**Issue by apaneto** [drbenvincent/delay-discounting-analysis#118]
I set the paths correctly, but it seems the script cannot add the toolbox subpaths. Any insight into this? 

projectPath = '~/Desktop/delay-discounting-analysis/demo';
toolboxPath = '~/Desktop/delay-discounting-analysis/ddToolbox';

Using Matlab R2014a

**Comment by drbenvincent** [comment]
Hi Adrian. I definitely appreciate bug reports by the way. Can you let me know more about the actual error you get and after which call you get the error? I'll try to get to the bottom of it

**Comment by apaneto** [comment]
I believe the error is when the script calls the addSubFoldersToPath() function

Error using setToolboxPath (line 19)
Some error in adding toolbox subpaths

---

EDU>> addSubFoldersToPath
Error using cell/strfind (line 32)
If any of the input arguments are cell arrays, the first must be a cell array of strings and the second
must be a character array.

Error in addSubFoldersToPath>isStringMatch (line 30)
matchFound = any(~cellfun('isempty',strfind(str,pattern)));

Error in addSubFoldersToPath>shouldAddThisPath (line 23)
    if isStringMatch(path,ignoreStr)

Error in addSubFoldersToPath (line 10)
    if shouldAddThisPath(allSubpaths(1,n),blacklist)

---

Does this help?

**Comment by drbenvincent** [comment]
Cant immediately see the problem. Maybe copy in the full code you're using? Although I'm actually very close to releasing a new version of the code with quite a few changes. Would it possible for you to switch to the dev branch and try out that latest code? If the problem goes way then that's great, otherwise I'll dig deeper.

Bear in mind that in this new (about to be released) version I've made changes to how the toolbox is called so, just a heads up about that.

**Comment by apaneto** [comment]
This is no longer an issue for me. I was able to work around it. Now I get the following error: 

Error using matjags/error_reporting (line 286)
Error from system environment: Fri Sep 23 14:50:36 EDT 2016
Welcome to JAGS 4.2.0 on Fri Sep 23 14:50:36 2016
JAGS is free software and comes with ABSOLUTELY NO WARRANTY
Loading module: basemod: ok
Loading module: bugs: ok
Reading data file /private/tmp/tp29b2e113_1c9c_49e3_8f95_1dac493aae39/jagsdata.R
Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Graph information:
   Observed stochastic nodes: 400
   Unobserved stochastic nodes: 486
   Total graph size: 18138

WARNING: Unused variable(s) in data table:
delayLookUp
uniqueDelays

Reading parameter file /private/tmp/tp29b2e113_1c9c_49e3_8f95_1dac493aae39/jagsinit1.R
Initializing model
Adapting 1000
Adaptation successful
Updating 5000
syntax error, unexpected DOUBLE, expecting INT

Error in matjags (line 138)
error_reporting();

Error in MatjagsWrapper/invokeSampler (line 57)
            [samples, stats] = matjags(...

Error in MatjagsWrapper/conductInference (line 44)
            mcmc = obj.invokeSampler();

Error in Model/conductInference (line 67)
            obj.mcmc = obj.sampler.conductInference( obj , obj.data );

I tried using full paths suggestion you provided another users without the (~/) and that did not solve the problem. 

-Adrian. 

Any idea on how long it would take to release? I am sitting on some data that I would like to analyze.

**Comment by drbenvincent** [comment]
I'm hoping to work on it over this weekend/Monday. Happy to have a Skype chat to just get it done together if you like. My username for that is the same as my username here.

**Comment by drbenvincent** [comment]
So this issue is no longer present in the current version of the code (in the dev branch). I'll be releasing a new version soon, so this is all wrapped up :)

**Comment by drbenvincent** [comment]
FYI. I've released v.1.4 now. It's worth upgrading... many changes including simplifying the way how analyses are called.
