### ISSUE TITLE
Plotting discountsurface plot

### ISSUE THREAD

**Issue by apaneto** [drbenvincent/delay-discounting-analysis#120]
Hi Ben, 

The new run_me.m file runs great. Thanks. It gets into a snag with creating the surface plot. The following error results: 

No public property 'mean' for class 'BivariateDistribution'.

Error in plotDiscountSurface (line 18)
mc = mcBivariate.(plotdata.pointEstimateType);

Error in make_experimentFigPlotFuncs_ME>@(plotdata)plotDiscountSurface(plotdata) (line 22)
experimentFigPlotFuncs{5} = @(plotdata) plotDiscountSurface(plotdata);

Error in apply_plot_function_to_subplot_handle (line 3)
func(plotdata);

Error in
figExperiment>@(n)apply_plot_function_to_subplot_handle(plotFuncs{n},subplot_handles(n),plotdata)

Error in figExperiment (line 24)
arrayfun(@(n) apply_plot_function_to_subplot_handle(plotFuncs{n}, subplot_handles(n), plotdata),...

Error in Model/plot (line 212)
                figExperiment(obj.experimentFigPlotFuncs, obj.pdata(p));

Error in Model/conductInference (line 106)
                obj.plot( 'shouldExportPlots', obj.shouldExportPlots )

Error in ModelHierarchicalME (line 30)
            obj = obj.conductInference();

Error in run_me (line 98)
% ModelMixedME

**Comment by drbenvincent** [comment]
This was down to a small error in the mcmc-utils-matlab repo which does some plotting. It's fixed now, and problem solved.
